<a href="https://colab.research.google.com/github/AnuruddhaPaul/ADV_PROG/blob/main/Assingment_Lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import time
from typing import List, Tuple, Any

In [10]:


# =============================================================================
# Q.1) Matrix Multiplication: Python Lists vs NumPy Arrays Performance Comparison
# =============================================================================

print("\n" + "=" * 80)
print("Q.1) MATRIX MULTIPLICATION PERFORMANCE COMPARISON")
print("=" * 80)

def matrix_multiply_lists(A: List[List[float]], B: List[List[float]]) -> List[List[float]]:

    n = len(A)
    m = len(B[0])
    p = len(B)


    result = [[0 for _ in range(m)] for _ in range(n)]


    for i in range(n):
        for j in range(m):
            for k in range(p):
                result[i][j] += A[i][k] * B[k][j]

    return result

def compare_matrix_multiplication():
    size = 100

    print(f"\nCreating {size}x{size} matrices...")
    matrix_list_A = [[np.random.rand() for _ in range(size)] for _ in range(size)]
    matrix_list_B = [[np.random.rand() for _ in range(size)] for _ in range(size)]

    matrix_numpy_A = np.array(matrix_list_A)
    matrix_numpy_B = np.array(matrix_list_B)


    print("\n" + "-" * 60)
    print("Method 1: Pure Python Lists")
    print("-" * 60)
    start_time = time.time()
    result_list = matrix_multiply_lists(matrix_list_A, matrix_list_B)
    end_time = time.time()
    list_time = end_time - start_time
    print(f"Execution Time: {list_time:.6f} seconds")


    print("\n" + "-" * 60)
    print("Method 2: NumPy Arrays")
    print("-" * 60)
    start_time = time.time()
    result_numpy = np.dot(matrix_numpy_A, matrix_numpy_B)
    end_time = time.time()
    numpy_time = end_time - start_time
    print(f"Execution Time: {numpy_time:.6f} seconds")

    # Performance Analysis
    print("\n" + "-" * 60)
    print("PERFORMANCE ANALYSIS")
    print("-" * 60)
    speedup = list_time / numpy_time
    print(f"NumPy is {speedup:.2f}x faster than pure Python lists")
    print(f"Time saved: {(list_time - numpy_time):.6f} seconds")


# Execute Q.1
compare_matrix_multiplication()


Q.1) MATRIX MULTIPLICATION PERFORMANCE COMPARISON

Creating 100x100 matrices...

------------------------------------------------------------
Method 1: Pure Python Lists
------------------------------------------------------------
Execution Time: 0.092586 seconds

------------------------------------------------------------
Method 2: NumPy Arrays
------------------------------------------------------------
Execution Time: 0.000417 seconds

------------------------------------------------------------
PERFORMANCE ANALYSIS
------------------------------------------------------------
NumPy is 222.03x faster than pure Python lists
Time saved: 0.092169 seconds


In [11]:
# =============================================================================
# Q.2) 2D NumPy Array Operations and Statistical Analysis
# =============================================================================
np.random.seed(42)
array_2d = np.random.randint(1, 101, size=(10, 5))

print("\nOriginal 10x5 Array:")
print(array_2d)

# i) Sum of odd numbers
print("\n" + "-" * 60)
print("i) Sum of Odd Numbers")
print("-" * 60)
odd_numbers = array_2d[array_2d % 2 != 0]
sum_odd = np.sum(odd_numbers)
print(f"Odd numbers: {odd_numbers}")
print(f"Sum of odd numbers: {sum_odd}")

# ii) Sum of even numbers
print("\n" + "-" * 60)
print("ii) Sum of Even Numbers")
print("-" * 60)
even_numbers = array_2d[array_2d % 2 == 0]
sum_even = np.sum(even_numbers)
print(f"Even numbers: {even_numbers}")
print(f"Sum of even numbers: {sum_even}")

# iii) Sum of diagonal elements
print("\n" + "-" * 60)
print("iii) Sum of Diagonal Elements")
print("-" * 60)

diagonal_elements = np.diagonal(array_2d)
sum_diagonal = np.sum(diagonal_elements)
print(f"Diagonal elements: {diagonal_elements}")
print(f"Sum of diagonal elements: {sum_diagonal}")

# iv) Transpose
print("\n" + "-" * 60)
print("iv) Transpose of the Array")
print("-" * 60)
transposed = array_2d.T
print(f"Transposed array shape: {transposed.shape}")
print(transposed)

# v) 2nd, 3rd, 4th, 5th and 6th rows
print("\n" + "-" * 60)
print("v) Rows 2-6 (indices 1-5)")
print("-" * 60)
rows_2_to_6 = array_2d[1:6]
print(rows_2_to_6)

# vi) Multiply rows 2-6 by -1
print("\n" + "-" * 60)
print("vi) Multiply Rows 2-6 by -1")
print("-" * 60)
array_2d_copy = array_2d.copy()
array_2d_copy[1:6] = array_2d_copy[1:6] * -1
print("Updated array:")
print(array_2d_copy)

# vii) Flatten the sub-matrix (rows 2-6)
print("\n" + "-" * 60)
print("vii) Flattened Sub-matrix (Rows 2-6)")
print("-" * 60)
flattened_submatrix = array_2d[1:6].flatten()
print(f"Flattened array: {flattened_submatrix}")
print(f"Shape: {flattened_submatrix.shape}")

# viii) Sum of all elements
print("\n" + "-" * 60)
print("viii) Sum of All Elements")
print("-" * 60)
total_sum = np.sum(array_2d)
print(f"Sum of all elements: {total_sum}")

# ix) Mean of all elements
print("\n" + "-" * 60)
print("ix) Mean of All Elements")
print("-" * 60)
mean_value = np.mean(array_2d)
print(f"Mean: {mean_value:.4f}")

# x) Median of all elements
print("\n" + "-" * 60)
print("x) Median of All Elements")
print("-" * 60)
median_value = np.median(array_2d)
print(f"Median: {median_value:.4f}")

# xi) Standard Deviation
print("\n" + "-" * 60)
print("xi) Standard Deviation of All Elements")
print("-" * 60)
std_dev = np.std(array_2d)
print(f"Standard Deviation: {std_dev:.4f}")

# xii) Flatten and sort entire array
print("\n" + "-" * 60)
print("xii) Flattened and Sorted Array")
print("-" * 60)
flattened_sorted = np.sort(array_2d.flatten())
print(f"Sorted flattened array: {flattened_sorted}")


Original 10x5 Array:
[[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]
 [ 76  58  22  89  49]
 [ 91  59  42  92  60]
 [ 80  15  62  62  47]
 [ 62  51  55  64   3]
 [ 51   7  21  73  39]]

------------------------------------------------------------
i) Sum of Odd Numbers
------------------------------------------------------------
Odd numbers: [93 15 61 21 83 87 75 75  3 53 21 33 89 49 91 59 15 47 51 55  3 51  7 21
 73 39]
Sum of odd numbers: 1270

------------------------------------------------------------
ii) Sum of Even Numbers
------------------------------------------------------------
Even numbers: [ 52  72  88 100  24  22   2  88  30  38   2  64  60  76  58  22  42  92
  60  80  62  62  62  64]
Sum of even numbers: 1322

------------------------------------------------------------
iii) Sum of Diagonal Elements
------------------------------------------------------------
Diagonal elements: [52 83 24 30 33]
Sum of d

In [12]:
# =============================================================================
# Q.3) Custom 2D Array Manager Class
# =============================================================================


class Array2DManager:


    def __init__(self, array: np.ndarray):

        if array.ndim != 2:
            raise ValueError("Array must be 2-dimensional")
        self.array = array

    def reverse_rows_elements(self) -> np.ndarray:

        return self.array[:, ::-1]

    def reverse_rows_order(self) -> np.ndarray:

        return self.array[::-1, :]

    def reverse_both(self) -> np.ndarray:

        return self.array[::-1, ::-1]

    def cut_perimeter(self) -> np.ndarray:

        if self.array.shape[0] <= 2 or self.array.shape[1] <= 2:
            raise ValueError("Array too small to cut perimeter")
        return self.array[1:-1, 1:-1]

    def display_all_operations(self):

        print("\nOriginal Array:")
        print(self.array)

        print("\na) Elements in each row reversed:")
        print(self.reverse_rows_elements())

        print("\nb) Rows in reverse order:")
        print(self.reverse_rows_order())

        print("\nc) Both rows and columns reversed:")
        print(self.reverse_both())

        try:
            print("\nd) Perimeter cut (first/last row and column removed):")
            print(self.cut_perimeter())
        except ValueError as e:
            print(f"\nd) Perimeter cut: Error - {e}")

# Test the Array2DManager class
test_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

manager = Array2DManager(test_array)
manager.display_all_operations()


Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

a) Elements in each row reversed:
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]

b) Rows in reverse order:
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

c) Both rows and columns reversed:
[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]

d) Perimeter cut (first/last row and column removed):
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [13]:
# =============================================================================
# Q.4) Solving Systems of Linear Equations using Inverse Matrix Method
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.4) SOLVING LINEAR EQUATIONS USING INVERSE MATRIX METHOD")
print("=" * 80)

def solve_linear_system(A: np.ndarray, B: np.ndarray, system_name: str):

    print(f"\n{system_name}")
    print("-" * 60)

    print("Coefficient Matrix A:")
    print(A)

    print("\nConstants Matrix B:")
    print(B)


    det_A = np.linalg.det(A)
    print(f"\nDeterminant of A: {det_A:.6f}")

    if abs(det_A) < 1e-10:
        print("Matrix is singular! System has no unique solution.")
        print("The equations are either inconsistent or dependent.")
        return None

    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)

    solution = np.dot(A_inv, B)

    print("\nSolution:")
    variables = ['x', 'y', 'z', 'w']
    for i, val in enumerate(solution):
        print(f"{variables[i]} = {val:.6f}")


    print("\nVerification (A * solution should equal B):")
    verification = np.dot(A, solution)
    print(f"A * solution = {verification}")
    print(f"Original B = {B}")
    print(f"Difference = {np.abs(verification - B)}")

    return solution


print("\nSystem i)")
A1 = np.array([[1, 2],
               [2, 4]], dtype=float)
B1 = np.array([-4, -8], dtype=float)
solve_linear_system(A1, B1, "System i: x + 2y = -4, 2x + 4y = -8")


print("\n\nSystem ii)")
A2 = np.array([[1, 2, 3],
               [2, -3, 2],
               [3, 1, -1]], dtype=float)
B2 = np.array([6, 14, -2], dtype=float)
solve_linear_system(A2, B2, "System ii: x + 2y + 3z = 6, 2x - 3y + 2z = 14, 3x + y - z = -2")




Q.4) SOLVING LINEAR EQUATIONS USING INVERSE MATRIX METHOD

System i)

System i: x + 2y = -4, 2x + 4y = -8
------------------------------------------------------------
Coefficient Matrix A:
[[1. 2.]
 [2. 4.]]

Constants Matrix B:
[-4. -8.]

Determinant of A: 0.000000
Matrix is singular! System has no unique solution.
The equations are either inconsistent or dependent.


System ii)

System ii: x + 2y + 3z = 6, 2x - 3y + 2z = 14, 3x + y - z = -2
------------------------------------------------------------
Coefficient Matrix A:
[[ 1.  2.  3.]
 [ 2. -3.  2.]
 [ 3.  1. -1.]]

Constants Matrix B:
[ 6. 14. -2.]

Determinant of A: 50.000000

Inverse of A:
[[ 0.02  0.1   0.26]
 [ 0.16 -0.2   0.08]
 [ 0.22  0.1  -0.14]]

Solution:
x = 1.000000
y = -2.000000
z = 3.000000

Verification (A * solution should equal B):
A * solution = [ 6. 14. -2.]
Original B = [ 6. 14. -2.]
Difference = [3.55271368e-15 3.55271368e-15 4.44089210e-16]


array([ 1., -2.,  3.])

In [14]:

# =============================================================================
# Q.5) Create 10x10 Array with 1s on Perimeter and 0s Inside
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.5) 10x10 ARRAY WITH 1s ON PERIMETER AND 0s INSIDE")
print("=" * 80)

# Method 1: Using zeros and slicing
perimeter_array = np.zeros((10, 10), dtype=int)
perimeter_array[0, :] = 1  # Top row
perimeter_array[-1, :] = 1  # Bottom row
perimeter_array[:, 0] = 1  # Left column
perimeter_array[:, -1] = 1  # Right column

print("\nArray with 1s on perimeter and 0s inside:")
print(perimeter_array)

# Method 2: Using ones and slicing (alternative approach)
print("\n\nAlternative Method:")
perimeter_array_alt = np.ones((10, 10), dtype=int)
perimeter_array_alt[1:-1, 1:-1] = 0
print(perimeter_array_alt)



Q.5) 10x10 ARRAY WITH 1s ON PERIMETER AND 0s INSIDE

Array with 1s on perimeter and 0s inside:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Alternative Method:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [15]:

# =============================================================================
# Q.6) Flatten 2D Array to 1D Without Built-in Functions
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.6) FLATTEN 2D ARRAY WITHOUT BUILT-IN FUNCTIONS")
print("=" * 80)

def manual_flatten(array_2d: np.ndarray) -> np.ndarray:

    rows, cols = array_2d.shape
    result = np.empty(rows * cols, dtype=array_2d.dtype)

    index = 0
    for i in range(rows):
        for j in range(cols):
            result[index] = array_2d[i, j]
            index += 1

    return result

# Test the function
test_array_flatten = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("\nOriginal 2D Array:")
print(test_array_flatten)

print("\nManually Flattened Array:")
flattened_manual = manual_flatten(test_array_flatten)
print(flattened_manual)

print("\nVerification using built-in flatten():")
print(test_array_flatten.flatten())

print("\nArrays are equal:", np.array_equal(flattened_manual, test_array_flatten.flatten()))



Q.6) FLATTEN 2D ARRAY WITHOUT BUILT-IN FUNCTIONS

Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Manually Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Verification using built-in flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Arrays are equal: True


In [16]:
# =============================================================================
# Q.7) Reverse Rows of 2D Array In-Place
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.7) REVERSE ROWS OF 2D ARRAY IN-PLACE")
print("=" * 80)

def reverse_rows_inplace(array: np.ndarray) -> None:

    n_rows = array.shape[0]


    for i in range(n_rows // 2):

        array[[i, n_rows - 1 - i]] = array[[n_rows - 1 - i, i]]


test_array_reverse = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print("\nOriginal Array:")
print(test_array_reverse)

reverse_rows_inplace(test_array_reverse)

print("\nArray After Reversing Rows In-Place:")
print(test_array_reverse)



Q.7) REVERSE ROWS OF 2D ARRAY IN-PLACE

Original Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array After Reversing Rows In-Place:
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [17]:
# =============================================================================
# Q.8) Create 8x8 Checkerboard Pattern
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.8) CREATE 8x8 CHECKERBOARD PATTERN")
print("=" * 80)

checkerboard3 = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))

print("\n: Using tile (most concise)")
print(checkerboard3)



Q.8) CREATE 8x8 CHECKERBOARD PATTERN

: Using tile (most concise)
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [18]:

# =============================================================================
# Q.9) 3D Array Slicing
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.9) 3D ARRAY SLICING - MIDDLE ROW OF EACH 2D SUBARRAY")
print("=" * 80)


array_3d = np.arange(1, 28).reshape(3, 3, 3)

print("\nOriginal 3D Array (3x3x3):")
print(array_3d)
print("\nShape:", array_3d.shape)

print("\nVisualization - Each 2D subarray:")
for i in range(3):
    print(f"\nSubarray {i}:")
    print(array_3d[i])

middle_rows = array_3d[:, 1, :]

print("\n" + "-" * 60)
print("Middle Row of Each 2D Subarray:")
print("-" * 60)
print(middle_rows)
print("\nShape:", middle_rows.shape)

print("\nExplanation:")
print("- array_3d[:, 1, :] means:")
print("  : - take all 2D subarrays (all along first dimension)")
print("  1 - take row at index 1 (middle row) from each subarray")
print("  : - take all columns")



Q.9) 3D ARRAY SLICING - MIDDLE ROW OF EACH 2D SUBARRAY

Original 3D Array (3x3x3):
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Shape: (3, 3, 3)

Visualization - Each 2D subarray:

Subarray 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subarray 1:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Subarray 2:
[[19 20 21]
 [22 23 24]
 [25 26 27]]

------------------------------------------------------------
Middle Row of Each 2D Subarray:
------------------------------------------------------------
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]

Shape: (3, 3)

Explanation:
- array_3d[:, 1, :] means:
  : - take all 2D subarrays (all along first dimension)
  1 - take row at index 1 (middle row) from each subarray
  : - take all columns


In [19]:



# =============================================================================
# Q.10) Find Common Elements Between Two Arrays Without Loops
# =============================================================================

print("\n\n" + "=" * 80)
print("Q.10) FIND COMMON ELEMENTS WITHOUT LOOPS")
print("=" * 80)


A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
B = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

print("\nArray A:")
print(A)

print("\nArray B:")
print(B)

common_elements = np.intersect1d(A, B)

print("\n" + "-" * 60)
print(" Using np.intersect1d()")
print("-" * 60)
print("Common elements:", common_elements)





Q.10) FIND COMMON ELEMENTS WITHOUT LOOPS

Array A:
[ 1  2  3  4  5  6  7  8  9 10]

Array B:
[ 5  6  7  8  9 10 11 12 13 14 15]

------------------------------------------------------------
 Using np.intersect1d()
------------------------------------------------------------
Common elements: [ 5  6  7  8  9 10]


In [20]:
print("="*60)